name: Deploy .NET app to GCP

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    name: Deploy application to GKE
    runs-on: self-hosted    # ubuntu-latest # Use GCP-hosted runner or self-hosted if preferred

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker image
        run: docker build -t githubactions-gke-demo:'${{ github.sha }}' .

      - name: Authenticate to Google Container Registry (GCR)
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY_1 }}
          gcloud config set account akhand@astral-subject-452906-a1.iam.gserviceaccount.com
          gcloud auth configure-docker

      - name: Tag and push Docker image to GCR
        run: |
          docker tag githubactions-gke-demo:'${{ github.sha }}' gcr.io/astral-subject-452906-a1/githubactions-gke-demo:'${{ github.sha }}'
          docker push gcr.io/astral-subject-452906-a1/githubactions-gke-demo:'${{ github.sha }}'

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --region ${{ secrets.GKE_REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy application to GKE
        run: kubectl apply -f k8s/
